services:
  srv_sensor:
    image: srv_sensor:latest
    container_name: srv_sensor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: aguas_network